# Generated by Django 4.2.3 on 2023-08-09 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_skill_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='desriotion',
            new_name='description',
        ),
    ]
