# Generated by Django 4.2.3 on 2023-10-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('is_read', 'created_at')},
        ),
    ]
