# Generated by Django 4.2.7 on 2023-11-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_message_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='id',
            new_name='temp_id',
        ),
    ]
