# Generated by Django 4.2.7 on 2023-11-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_id_profile_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='temp_id',
            new_name='id',
        ),
    ]
