# Generated by Django 4.2.7 on 2023-11-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_temp_id_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='id',
            new_name='temp_id',
        ),
    ]
