# Generated by Django 4.2.7 on 2023-11-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_id_skill_temp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='temp_id',
            new_name='id',
        ),
    ]
