# Generated by Django 4.2.3 on 2023-08-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_vote_ratio_project_vote_total_reviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_lik',
            new_name='demo_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='source_likn',
            new_name='source_link',
        ),
    ]
