# Generated by Django 4.2.3 on 2023-10-04 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_desriotion_skill_description'),
        ('projects', '0005_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
