# Generated by Django 4.2.3 on 2023-10-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_desriotion_skill_description'),
        ('projects', '0006_reviews_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('owner', 'project')},
        ),
    ]
