# Generated by Django 4.2.3 on 2023-10-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_vote_ratio_project_vote_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
