# Generated by Django 4.2.3 on 2023-10-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_reviews_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='is_read',
        ),
    ]
